### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by uppinder** [razimantv/mazegenerator#1]
When running make I get this error:
```
circularhexagonmaze.cpp: In member function ‘virtual std::tuple<double, double, double, double> CircularHexagonMaze::GetCoordinateBounds() const’:
circularhexagonmaze.cpp:45:39: error: converting to ‘std::tuple<double, double, double, double>’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {int, int, const int&, const int&}; <template-parameter-2-2> = void; _Elements = {double, double, double, double}]’
   return {-size_, -size_, size_, size_};
                                       ^
makefile:15: recipe for target 'circularhexagonmaze.o' failed
make: *** [circularhexagonmaze.o] Error 1

```
Compiler used: 
```
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
```

I tried changing c++11 to c++17 (according to notes in http://en.cppreference.com/w/cpp/utility/tuple), but It still gave the same error.
It compiled successfully by replacing list-initialization with std::make_tuple in the project.

**Comment by razimantv** [comment]
Thank you for pointing out the issue, which compiler do you use?

**Comment by uppinder** [comment]
I've updated the above comment.

**Comment by razimantv** [comment]
Fixed in the [latest commit](https://github.com/razimantv/mazegenerator/commit/a5ac028da360a4e8b92b3a66de9fb71b82f4711e).

**Comment by razimantv** [comment]
Fixed in the[ latest commit](https://github.com/razimantv/mazegenerator/commit/a5ac028da360a4e8b92b3a66de9fb71b82f4711e).
